# Generated by Django 4.2.2 on 2025-07-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(
                help_text="Укажите почту",
                max_length=10,
                unique=True,
                verbose_name="Почта",
            ),
        ),
    ]
