# Generated by Django 4.2.2 on 2025-07-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Укажите почту",
                max_length=50,
                unique=True,
                verbose_name="Почта",
            ),
        ),
    ]
