# Generated by Django 4.2.2 on 2025-07-06 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="users",
            new_name="user",
        ),
    ]
