# Generated by Django 4.2.2 on 2025-07-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_payment_user_payment_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date_payment",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Дата оплаты"
            ),
        ),
    ]
