# Generated by Django 4.2.2 on 2025-07-14 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0012_alter_lesson_video"),
        ("users", "0010_subscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={"verbose_name": "подписка", "verbose_name_plural": "подписки"},
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together={("sub_user", "sub_course")},
        ),
    ]
