# Generated by Django 4.2.2 on 2025-07-17 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_payment_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="email",
            new_name="user",
        ),
    ]
