version: '3.9'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "6380:6379"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - .static_volume:/app/staticfile
    depends_on:
      - web
  wed:
    build: .
    command: sh -c "python3 manage.py collectstatic --noinput && gunicorn config.wsgi:aplication --bind 0.0.0.0.8000"
    volumes:
      - .:/app
      - static_volume:/app/static
    expose:
      - "8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

  db:
    image: postgres:16
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

redis:
  image: redis:7
  volimes:
    - redis_data:/data
  env_file:
    - ./.env

volumes:
  postgres_data:
  static_volume:
  redis_data:
