version: '3.9'

services:
  wed:
    build: .
    command: python3 manage.py runserver 0.0.0.0.8000
    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - "5432:5432"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17.0
    env_file:
      - .env
    volumes:
      - postgres/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  default:

volumes:
  postgres_data:
  static_volume:
