# Generated by Django 4.2.2 on 2025-06-25 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="lesson",
            new_name="course",
        ),
    ]
