# Generated by Django 4.2.2 on 2025-07-05 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_rename_lesson_lesson_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="course",
        ),
        migrations.AddField(
            model_name="course",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="materials.lesson",
                verbose_name="Урок",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите видео",
                null=True,
                upload_to="materials/video",
                verbose_name="Ссылка на видео",
            ),
        ),
    ]
