# Generated by Django 4.2.2 on 2025-07-10 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_remove_lesson_course_course_lesson_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="lesson",
        ),
        migrations.AddField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="materials.course",
                verbose_name="Урок",
            ),
        ),
    ]
