# Generated by Django 4.2.2 on 2025-07-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_alter_lesson_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video",
            field=models.CharField(
                blank=True,
                help_text="Загрузите видео",
                max_length=100,
                null=True,
                verbose_name="Ссылка на видео",
            ),
        ),
    ]
