# Generated by Django 4.2.2 on 2025-07-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0008_alter_lesson_course"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="course",
            new_name="courses",
        ),
    ]
