# Generated by Django 4.2.2 on 2025-07-21 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0012_alter_lesson_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="update",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Время обновления курса"
            ),
        ),
    ]
