# Generated by Django 4.2.2 on 2025-07-21 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0014_alter_course_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="update",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Время обновления курса",
            ),
        ),
    ]
