# Generated by Django 4.2.2 on 2025-07-21 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0015_alter_course_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="update",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime.now,
                null=True,
                verbose_name="Время обновления курса",
            ),
        ),
    ]
